name: Merge Staging to Production

on:
  push:
    branches:
      - 'staging'

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Checkout the repository code

      - name: Merge Staging -> Production
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: production
          message: 'Automated merge from staging to production'
          github_token: ${{ secrets.IL8_CI_CD }}  # Use your Personal Access Token (PAT)
