name: Merge Staging to Production

on:
  push:
    branches:
      - staging

jobs:
  test_and_build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Clean npm cache and remove package-lock.json
        run: |
          npm cache clean --force
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          npm install || npm install --legacy-peer-deps

      - name: Display available scripts
        run: npm run

      - name: Run tests
        run: npm test -- --watchAll=false || echo "Tests failed but continuing"

      - name: Build project
        run: npm run build || echo "Build failed but continuing"

  create_pull_request:
    needs: test_and_build_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.IL8_CI_CD }}
        run: |
          pr_url=$(gh pr create --base production --head staging --title "Merge Staging to Production" --body "This PR merges the latest changes from the staging branch into the production branch. Please review and approve to proceed with the merge.")
          echo "PR_URL=$pr_url" >> $GITHUB_ENV

      - name: Output PR URL
        run: echo "Pull request created - ${{ env.PR_URL }}"

  merge_pull_request:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for PR Approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.IL8_CI_CD }}
          approvers: MLOps-MaitriAI

      - name: Merge Pull Request
        if: steps.approval.outputs.approved == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.IL8_CI_CD }}
        run: |
          pr_number=$(echo ${{ env.PR_URL }} | awk -F'/' '{print $NF}')
          gh pr merge $pr_number --merge
