name: Create Pull Request to Production

on:
  push:
    branches:
      - staging

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request to Production
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.IL8_CI_CD }}  # Use the renamed PAT secret
          title: 'Merge staging into production'
          body: 'Automated pull request to merge changes from staging to production.'
          base: 'production'  # Target branch
          branch: 'create-pull-request/staging-to-production'  # This will be the auto-created branch name
