name: Merge Staging to Production (Excluding .github)

on:
  push:
    branches:
      - staging

jobs:
  test_and_build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Clean npm cache and remove package-lock.json
        run: |
          npm cache clean --force
          rm -f package-lock.json
      - name: Install dependencies
        run: |
          npm install || npm install --legacy-peer-deps
      - name: Display available scripts
        run: npm run
      - name: Run tests
        run: npm test -- --watchAll=false || echo "Tests failed but continuing"
      - name: Build project
        run: npm run build || echo "Build failed but continuing"

  create_pull_request:
    needs: test_and_build_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create temporary branch without .github folder
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b temp-staging-branch staging
          git rm -r --cached .github
          git commit -m "Remove .github folder for merging"
          git push origin temp-staging-branch
      - name: Debug information
        run: |
          git branch -a
          git log --oneline -n 5 production
          git log --oneline -n 5 temp-staging-branch
          git diff production temp-staging-branch
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.IL8_CI_CD }}
        run: |
          # Ensure branches are up-to-date
          git fetch origin production:production
          git fetch origin temp-staging-branch:temp-staging-branch
          
          # Check if there are any differences
          if git diff --quiet production temp-staging-branch; then
            echo "No differences found between production and temp-staging-branch"
            exit 0
          fi
          
          # Create PR
          pr_url=$(gh pr create --base production --head temp-staging-branch --title "Merge Staging to Production (Excluding .github)" --body "This PR merges the latest changes from the staging branch into the production branch, excluding the .github folder. Please review and approve to proceed with the merge.")
          echo "PR_URL=$pr_url" >> $GITHUB_ENV
      - name: Output PR URL
        run: echo "Pull request created - ${{ env.PR_URL }}"

  merge_pull_request:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Wait for PR Approval
        id: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.IL8_CI_CD }}
          approvers: MLOps-MaitriAI
      - name: Merge Pull Request
        if: steps.approval.outputs.approved == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.IL8_CI_CD }}
        run: |
          pr_number=$(echo ${{ env.PR_URL }} | awk -F'/' '{print $NF}')
          gh pr merge $pr_number --merge
      - name: Cleanup temporary branch
        if: steps.approval.outputs.approved == 'true'
        run: |
          git push origin --delete temp-staging-branch
