name: Merge Staging to Production

on:
  push:
    branches:
      - staging

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.IL8_CI_CD }}
          branch: merge-staging-to-production
          base: production
          title: Merge Staging to Production
          body: |
            This PR merges the latest changes from the staging branch into the production branch.
            Please review and approve to proceed with the merge.

  merge_pull_request:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for PR Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.IL8_CI_CD }}
          approvers: MLOps-MaitriAI

      - name: Merge Pull Request
        if: steps.approval.outputs.approved == 'true'
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.IL8_CI_CD }}
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Merge staging into production"
          MERGE_DELETE_BRANCH: "true"